### ISSUE TITLE
The result of the speech did not show up in my UI

### ISSUE THREAD

**Issue by nardeuibnida** [EricBatlle/UnityAndroidSpeechRecognizer#16] opened 2023-06-19 15:15 UTC
Hi! Thank you for the plugin. I have an issue after I implementing your scripts to my own UI. My build apk does not record any speech after I record my voice. Is there some unity setting for it? My device is Samsung A02s and the app has microphone permission. I am using Microsoft Visual Studio 2019 to write all my scripts. Thanks a lot for your help!

**Comment by EricBatlle** [comment] 2023-06-19 15:53
Hello!
Do you have any logcat or Unity logs so I can dig Up a little bit on what's going on?

If you run the plugin on the editor It show some warning? So we can know if the issue is about your integration on the plugin in your project or something external.

**Comment by nardeuibnida** [comment] 2023-06-19 20:26
![Unity Log](https://github.com/EricBatlle/UnityAndroidSpeechRecognizer/assets/84713922/4241938a-2f4f-44ea-9794-30ff1a3872b1)

Here it is. There's no error just a warning.

**Comment by EricBatlle** [comment] 2023-06-20 11:03
Okey that's expected, and did you try to debug the build? Show me the logcats please

**Comment by nardeuibnida** [comment] 2023-06-20 11:58
I am sorry, do you mean debug the build in Visual Studio? I only play the scene in Unity to test the UI. And one more, where to find the logcats? Is it in Visual Studio?

**Comment by EricBatlle** [comment] 2023-06-20 13:51
On Android Studio: https://developer.android.com/studio/command-line/logcat?hl=es-419

**Comment by nardeuibnida** [comment] 2023-06-20 14:27
I am sorry to ask, if your project compatible with Visual Studio because I do my project in Unity and scripting in Visual Studio. No Android Studio used in my project.

**Comment by EricBatlle** [comment] 2023-06-20 19:57
But if you want to debug an apk on your device or a virtual one, you need to use Android Studio or use the Android Logcat Package: https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@0.1/manual/index.html 

I've never used this package, I always debug android builds with Android Studio.

**Comment by EricBatlle** [comment] 2023-07-05 16:34
Since there haven't been any recent updates, I am going to close this issue.

@nardeuibnida  if you're still experiencing this problem and want to continue the discussion just leave a comment here and I'll be happy to re-open this.

**Closed as completed by EricBatlle** 2023-07-05 16:34 UTC
