### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TrueSoSense** [EricBatlle/UnityAndroidSpeechRecognizer#11] opened 2023-02-15 21:36 UTC
Assets\Scripts\SpeechRecognizerPlugin_Editor.cs(16,9): error CS0246: The type or namespace name 'SpeechRecognizer' could not be found (are you missing a using directive or an assembly reference?)

and

Assets\Scripts\SpeechRecognizerPlugin_Editor.cs(16,73): error CS0246: The type or namespace name 'SpeechRecognizer' could not be found (are you missing a using directive or an assembly reference?)

**Comment by EricBatlle** [comment] 2023-02-18 23:26
Seems like you have an asmdef or something similar that do not allow the code to reach certain classes, in this case "SpeechRecognizer". This, or that you did not import the class "SpeechRecognizer" to your project.

But with this little issue information that you provide, I can't go further.

**Comment by frishtik** [comment] 2023-03-05 15:58
I have the same issue actually. I imported the package as described, and everything seems to be fine until I attach the files to Unity and the above mentioned errors appear. I believe the issue is not inability to access the classes. Maybe we should call SpeechRecognizerPlugin instead of SpeechRecognizer or something else?

**Comment by EricBatlle** [comment] 2023-03-05 16:00
> I have the same issue actually. I imported the package as described, and everything seems to be fine until I attach the files to Unity and the above mentioned errors appear. I believe the issue is not inability to access the classes. Maybe we should call SpeechRecognizerPlugin instead of SpeechRecognizer or something else?

Could you please provide an example project? I'm unable to reproduce your issue

**Comment by frishtik** [comment] 2023-03-05 16:12
sure. I uploaded it to Github here: https://github.com/frishtik/Talking-Tom-Clone-Unity.git

What I'm trying to do is make the GameController listen to the user and end when user is done speaking (and then use the text retrieved using other methods, not yet written).
I believe this is exactly what your repo is about (which I'm glad you created!), so I'd love if you identify the problem causing this issue. Thanks!

**Comment by EricBatlle** [comment] 2023-03-05 16:13
@frishtik and @TrueSoSense , thanks for reporting the issue, seems like the .package file do not contains [SpeechRecognizer](https://github.com/EricBatlle/UnityAndroidSpeechRecognizer/blob/master/UnitySpeechRecognizer/Assets/Scripts/SpeechRecognizer.cs) class.

I'll update the package link, but meanwhile if you are in a hurry, you can simply copy-past the SpeechRecognizer script attached on the link below.

**Comment by EricBatlle** [comment] 2023-03-05 16:28
Fixed in: b0ca7355d51471ea8df93043d29d898c44314fc0

**Closed by EricBatlle** 2023-03-05 16:28 UTC
Labels: on-hold
